channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - configparser==5.3.0
  - importlib-metadata==6.0.0
  - lz4==4.3.2
  - numpy==1.26.2
  - pandas==2.1.4
  - psutil==5.9.0
  - scikit-learn==1.3.1
  - scipy==1.11.4
  - typing-extensions==4.7.1
  - xgboost==1.7.3
name: mlflow-env
